apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
